POST http://localhost:8080/save/empl
Content-Type: application/json

{
  "employment_id": "2",
  "start_dt": "2020-08-04",
  "end_dt": "2020-10-03",
  "version": "4",
  "organization_name": "ООО ЭйТи Консальтинг",
  "position_name": "Аналитик",
  "person_id": "6"
}
